on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    # Every Monday at 09:00 on Monday
    # https://crontab.guru/#00_09_*_*_1
    - cron:  '00 09 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install
        run: npm install --no-package-lock
      - name: Test
        run: npm test
      - name: Report
        run: mkdir -p coverage && npx nyc report --reporter=text-lcov > coverage/lcov.info
      - name: Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
